# Scaffolding generated by Casein v5.1.1.5

module Casein
  class PaymentPartsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Payment parts'
  		@payment_parts = PaymentPart.order(sort_order(:payment_header_id)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View payment part'
      @payment_part = PaymentPart.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new payment part'
    	@payment_part = PaymentPart.new
    end

    def create
      @payment_part = PaymentPart.new payment_part_params
    
      if @payment_part.save
        flash[:notice] = 'Payment part created'
        redirect_to casein_payment_parts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new payment part'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update payment part'
      
      @payment_part = PaymentPart.find params[:id]
    
      if @payment_part.update_attributes payment_part_params
        flash[:notice] = 'Payment part has been updated'
				@payment_header = PaymentHeader.find @payment_part.payment_header_id
        redirect_to casein_payment_header_path(@payment_header)
      else
        flash.now[:warning] = 'There were problems when trying to update this payment part'
				@payment_header = PaymentHeader.find @payment_part.payment_header_id
        #redirect_to casein_payment_header_path(@payment_header)
				#todo controller => が効かない
        render :controller => :payment_header, :action => :show
      end
    end
 
    def destroy
      @payment_part = PaymentPart.find params[:id]
			@payment_header = PaymentHeader.find @payment_part.payment_header_id

      @payment_part.destroy
      flash[:notice] = 'Payment part has been deleted'
      #redirect_to casein_payment_parts_path
      redirect_to casein_payment_header_path(@payment_header)
    end
  
    private
      
      def payment_part_params
        params.require(:payment_part).permit(:payment_header_id, :item_id, :amount)
      end

  end
end
